"use strict";
const fs=require("fs"),path=require("path");const{fork}=require("child_process");const{app,BrowserWindow}=require("electron");const{ViewerWindow,ViewerTool,findBinDir}=require("geokernel-electron");const{ensureSampleFile}=require("../common/sample-data");
const URL="https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/stockholm_data.zip",C={RUN:1,CLASS:2,LIMIT:3,FILTER:4};let viewer,keeper,pump,worker,parquet="",busy=false,sequence=0,seen=false,hidden=0,buildingClass="apartments",maximumResults=25000;
function human(v){return v>=1048576?(v/1048576).toFixed(2)+" MiB":(v/1024).toFixed(1)+" KiB";}function reduce(a,b){return a?100*(1-b/a):0;}
function report(r,m){const e=r.optimized.elapsedMs+m,s=e?r.baseline.elapsedMs/e:0;return["DUCKDB GEOPARQUET ANALYTICS","","Dataset: stockholm_buildings.parquet","Dataset rows: "+r.datasetRows,"Filter: class = '"+r.className+"'","BBOX: 18.04, 59.30, 18.10, 59.35","Result rows: "+r.optimized.resultRows,"","FULL TRANSFER + APPLICATION FILTER","Rows transferred: "+r.baseline.sourceRows,"Columns transferred: "+r.baseline.columns,"Payload approximation: "+human(r.baseline.payloadBytes),"Elapsed: "+r.baseline.elapsedMs+" ms","","DUCKDB PUSHDOWN","Rows transferred: "+r.optimized.sourceRows,"Columns transferred: "+r.optimized.columns,"Payload approximation: "+human(r.optimized.payloadBytes),"Elapsed + Viewer materialization: "+e+" ms","","MEASURED GAIN","Speedup: "+s.toFixed(2)+"x","Row transfer reduction: "+reduce(r.baseline.sourceRows,r.optimized.sourceRows).toFixed(2)+"%","Payload reduction: "+reduce(r.baseline.payloadBytes,r.optimized.payloadBytes).toFixed(2)+"%","","The optimized path pushes class, BBOX, projection and limit into DuckDB before WKB crosses into the Viewer."].join("\n");}
function run(){if(!viewer||busy||!parquet)return;busy=true;viewer.setCommandEnabled(1,false);viewer.setControlEnabled(C.RUN,false);viewer.clearLog();viewer.appendLog("Running full transfer and DuckDB pushdown paths...");viewer.setStatusText("Benchmark running in background...");worker.send({type:"compare",id:++sequence,path:parquet,className:buildingClass,limit:maximumResults});}
function controlChanged(id,numericValue,textValue){if(id===C.CLASS)buildingClass=textValue||"apartments";else if(id===C.LIMIT)maximumResults=Math.max(1,Math.min(100000,Math.round(numericValue||25000)));else if(id===C.RUN)setImmediate(run);}
function done(m){if(!viewer||m.id!==sequence)return;busy=false;viewer.setCommandEnabled(1,true);viewer.setControlEnabled(C.RUN,true);if(m.type==="error"){viewer.clearLog();viewer.appendLog(m.message);viewer.setStatusText("Comparison failed.");return;}const started=Date.now(),rings=[];for(const raw of m.result.geometries){const wkb=Buffer.isBuffer(raw)?raw:Buffer.from(raw.data),g=viewer.readWkbGeometry(wkb);for(const part of g.parts||[])if(part.length)rings.push(part.map(p=>({x:+p.x,y:+p.y})));}viewer.clearLayers();viewer.addPolygonLayer("DuckDB pushdown result",rings,{fillColor:"#65B8E8",lineColor:"#176B9C",lineWidth:0.8});viewer.fullExtent();viewer.clearLog();viewer.appendLog(report(m.result,Date.now()-started));viewer.setStatusText("Comparison completed.");}
function startPump(){pump=setInterval(()=>{if(!viewer)return;viewer.processEvents();if(viewer.isVisible()){seen=true;hidden=0;}else if(seen){if(!hidden)hidden=Date.now();if(Date.now()-hidden>750)app.quit();}},16);}
async function start(){const bin=findBinDir(),dll=path.join(bin,process.platform==="win32"?"GeoKernel.Data.DuckDB.dll":"libGeoKernel.Data.DuckDB.so");if(!fs.existsSync(dll))throw new Error("GeoKernel.Data.DuckDB runtime is missing.");keeper=new BrowserWindow({width:1,height:1,show:false,skipTaskbar:true,webPreferences:{sandbox:true}});viewer=new ViewerWindow({title:"DuckDbGeoParquetAnalytics",width:1220,height:790});viewer.addCommandToolbar([{id:1,text:"Run measured comparison",enabled:false}],run);viewer.addControlPanel({title:"DuckDB GeoParquet analytics",area:"right",width:390,controls:[{id:C.RUN,type:"button",text:"Run measured comparison",enabled:false},{id:C.CLASS,type:"combo",label:"Building class",options:["apartments","residential","house"],value:"apartments"},{id:C.LIMIT,type:"number",label:"Maximum results",value:25000,minimum:1,maximum:100000,step:5000,decimals:0},{id:C.FILTER,type:"text",label:"Spatial filter",value:"Central Stockholm BBOX",readOnly:true}]},controlChanged);viewer.addLogPanel("Measured comparison");viewer.appendLog("Press Run measured comparison.\n\nThe baseline transfers every row and filters in the application. The optimized path pushes predicate, BBOX, projection and limit into DuckDB.");viewer.setTool(ViewerTool.PAN);viewer.setStatusText("Preparing Stockholm GeoParquet data...");viewer.show();viewer.processEvents();startPump();parquet=await ensureSampleFile(URL,"stockholm_data.zip",".",path.join("stockholm_data","stockholm_buildings.parquet"));worker=fork(path.join(__dirname,"analytics-worker.js"),[],{env:{...process.env,ELECTRON_RUN_AS_NODE:"1"},stdio:["ignore","pipe","pipe","ipc"]});worker.stdout.on("data",d=>process.stdout.write(d));worker.stderr.on("data",d=>process.stderr.write(d));worker.on("message",done);viewer.setCommandEnabled(1,true);viewer.setControlEnabled(C.RUN,true);viewer.setStatusText("Ready: "+path.basename(parquet));}
function stop(){if(pump)clearInterval(pump);worker?.kill();if(viewer)try{viewer.close();}catch{}viewer=null;keeper?.destroy();}
module.exports={start,stop};
