"use strict";

const fs = require("fs"); const path = require("path"); const { fork } = require("child_process"); const { app, BrowserWindow } = require("electron");
const { ViewerEventType, ViewerTool, ViewerWindow, findBinDir } = require("geokernel-electron"); const { ensureSampleFile } = require("../common/sample-data");
const SAMPLE_URL = "https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/stockholm.zip";
const COLORS = ["#2563EB", "#F97316", "#9333EA", "#0891B2", "#DB2777", "#65A30D", "#CA8A04", "#4F46E5"];
const COMMAND = Object.freeze({ NEW: 1, OPTIMIZE: 2 }); const CONTROL = Object.freeze({ NEW: 1, OPTIMIZE: 2, COUNT: 3, VEHICLE: 4, ROAD: 5, SUMMARY: 6 });
let viewer = null; let keeperWindow = null; let eventPump = null; let worker = null; let visibleOnce = false; let hiddenSince = 0; let closing = false; let ready = false; let busy = false; let sequence = 0; let pending = 0;
let stops = []; let stopNodes = []; let result = null; let vehicleCount = 1; let selectedVehicle = -1; let highlight = null; let vehicleOptions = []; let roadOptions = [];
function verifyQtPlatformPlugin() { const bin = findBinDir(); const candidates = [process.env.QT_QPA_PLATFORM_PLUGIN_PATH ? path.join(process.env.QT_QPA_PLATFORM_PLUGIN_PATH, "qwindows.dll") : null, path.join(bin, "platforms", "qwindows.dll"), path.join(bin, "plugins", "platforms", "qwindows.dll")].filter(Boolean); if (!candidates.some(fs.existsSync)) throw new Error(`Qt platform plugin is missing: ${bin}`); }
function canOptimize() { return ready && !busy && stopNodes.length >= 3; }
function updateEnabled() { const enabled = canOptimize(); viewer.setCommandEnabled(COMMAND.OPTIMIZE, enabled); viewer.setControlEnabled(CONTROL.OPTIMIZE, enabled); }
function setVehicleOptions(options) { vehicleOptions = options; viewer.setControlOptions(CONTROL.VEHICLE, options); viewer.setControlEnabled(CONTROL.VEHICLE, options.length > 0); }
function setRoadOptions(options) { roadOptions = options; viewer.setControlOptions(CONTROL.ROAD, options); viewer.setControlEnabled(CONTROL.ROAD, options.length > 0); }
function summaryText() { if (!result) return "Select a depot and at least two visits."; return `${result.vehicles.length} vehicles • ${result.visitCount} visits | Fleet distance: ${(result.totalDistance / 1000).toFixed(2)} km | Longest route: ${(result.longestDistance / 1000).toFixed(2)} km | Combined driving time: ${(result.totalTime / 60).toFixed(1)} min`; }
function draw() { if (!viewer) return; viewer.clearShapes(); if (result) result.vehicles.forEach((v, i) => viewer.addPolylineShape(v.geometry, { lineColor: COLORS[i % COLORS.length], lineOpacity: i === selectedVehicle ? 255 : 135, lineWidth: i === selectedVehicle ? 5 : 3 })); if (highlight?.length > 1) { viewer.addPolylineShape(highlight, { lineColor: "#FFD60A", lineOpacity: 220, lineWidth: 10 }); viewer.addPolylineShape(highlight, { lineColor: "#DC2626", lineOpacity: 255, lineWidth: 4 }); } stops.forEach((p, i) => { const depot = i === 0; viewer.addPointShape(p.x, p.y, { pointColor: depot ? "#22C55E" : "#F59E0B", lineColor: depot ? "#14532D" : "#78350F", pointSize: 18, lineWidth: 2 }); viewer.addTextShape(p.x, p.y, depot ? "D" : String(i), { textColor: "#FFFFFF", fontSize: 8, bold: true }); }); viewer.invalidateRenderCache(false, true); viewer.refreshLayers(); }
function reset() { if (!ready || !viewer) return; stops = []; stopNodes = []; result = null; selectedVehicle = -1; highlight = null; vehicleCount = 1; busy = false; viewer.setControlValue(CONTROL.COUNT, 1); viewer.setControlValue(CONTROL.SUMMARY, summaryText()); viewer.clearLog(); setVehicleOptions([]); setRoadOptions([]); updateEnabled(); draw(); viewer.setTool(ViewerTool.ROUTE); viewer.setStatusText("Click the map to select the depot."); }
function requestSelection(event) { if (!ready || busy || event.intValue !== ViewerTool.ROUTE) return; const world = viewer.screenToWorld(event.screenRectangle.left, event.screenRectangle.top); if (!world) return; busy = true; updateEnabled(); pending = ++sequence; viewer.setStatusText("Snapping the selected point..."); worker.send({ type: "select", id: pending, point: viewer.transformPoint(3857, 4326, world.x, world.y), lastNode: stopNodes.at(-1) ?? null }); }
function optimize() { if (!canOptimize()) return; busy = true; updateEnabled(); pending = ++sequence; result = null; selectedVehicle = -1; highlight = null; setVehicleOptions([]); setRoadOptions([]); viewer.clearLog(); draw(); viewer.setStatusText("Optimizing service vehicle routes..."); worker.send({ type: "optimize", id: pending, stops: stopNodes, vehicleCount: Math.min(vehicleCount, stops.length - 1) }); }
function showVehicle(index) { if (!result || index < 0 || index >= result.vehicles.length) return; selectedVehicle = index; const vehicle = result.vehicles[index]; highlight = vehicle.geometry; roadOptions = vehicle.steps.map((s, i) => `${i + 1}. ${s.name} • ${s.distance >= 1000 ? `${(s.distance / 1000).toFixed(1)} km` : `${s.distance.toFixed(0)} m`}`); setRoadOptions(roadOptions); viewer.clearLog(); viewer.appendLog(`Vehicle ${index + 1}: D → ${vehicle.visitLabels.join(" → ")} → D\n${(vehicle.distance / 1000).toFixed(2)} km • ${(vehicle.time / 60).toFixed(1)} min\n`); vehicle.steps.forEach((s, i) => viewer.appendLog(`${i + 1}. ${s.name}\n    ${s.distance >= 1000 ? `${(s.distance / 1000).toFixed(1)} km` : `${s.distance.toFixed(0)} m`}`)); draw(); }
function selectRoad(text) { const i = roadOptions.indexOf(text); highlight = i >= 0 ? result?.vehicles[selectedVehicle]?.steps[i]?.geometry ?? null : null; draw(); }
function handleWorker(message) { if (!viewer || closing) return; if (message.type === "ready") { ready = true; viewer.setCommandEnabled(COMMAND.NEW, true); viewer.setControlEnabled(CONTROL.NEW, true); reset(); return; } if (message.type === "error") { busy = false; updateEnabled(); viewer.setStatusText(message.message); console.error(message.message); return; } if (message.id !== pending) return; busy = false;
  if (message.type === "selection") { if (!message.snapped) { updateEnabled(); viewer.setStatusText("No reachable road node was found near this point."); return; } if (stopNodes.at(-1) === message.snapped.id) { updateEnabled(); return; } stopNodes.push(message.snapped.id); stops.push(message.snapped.world); result = null; highlight = null; selectedVehicle = -1; vehicleCount = Math.min(vehicleCount, Math.max(1, stops.length - 1)); viewer.setControlValue(CONTROL.SUMMARY, summaryText()); setVehicleOptions([]); setRoadOptions([]); viewer.clearLog(); updateEnabled(); draw(); viewer.setStatusText(stops.length === 1 ? "Depot selected. Click the map to add visits." : `Visit ${stops.length - 1} added. Add another visit or optimize.`); return; }
  if (message.type === "optimization") { updateEnabled(); if (message.result.error) { viewer.setStatusText(message.result.error); return; } result = message.result; selectedVehicle = 0; highlight = null; vehicleOptions = result.vehicles.map((v, i) => `Vehicle ${i + 1}: D → ${v.visitLabels.join(" → ")} → D | ${(v.distance / 1000).toFixed(2)} km • ${(v.time / 60).toFixed(1)} min`); setVehicleOptions(vehicleOptions); viewer.setControlValue(CONTROL.SUMMARY, summaryText()); viewer.setControlValue(CONTROL.VEHICLE, vehicleOptions[0]); showVehicle(0); viewer.setStatusText("Routes optimized for all service vehicles."); }
}
function onCommand(id) { setImmediate(() => { if (id === COMMAND.NEW) reset(); else if (id === COMMAND.OPTIMIZE) optimize(); }); }
function onControl(id, number, text) { setImmediate(() => { if (id === CONTROL.NEW) reset(); else if (id === CONTROL.OPTIMIZE) optimize(); else if (id === CONTROL.COUNT) { vehicleCount = Math.max(1, Math.floor(number || 1)); } else if (id === CONTROL.VEHICLE) showVehicle(vehicleOptions.indexOf(text)); else if (id === CONTROL.ROAD) selectRoad(text); }); }
function startEventPump() { eventPump = setInterval(() => { if (!viewer) return; viewer.processEvents(); if (viewer.isVisible()) { visibleOnce = true; hiddenSince = 0; } else if (visibleOnce) { if (!hiddenSince) hiddenSince = Date.now(); if (Date.now() - hiddenSince > 750) app.quit(); } }, 16); }
async function start() { closing = false; verifyQtPlatformPlugin(); keeperWindow = new BrowserWindow({ width: 1, height: 1, show: false, skipTaskbar: true, webPreferences: { sandbox: true } }); viewer = new ViewerWindow({ title: "RouteOptimization", width: 1200, height: 760 }); viewer.addCommandToolbar([{ id: COMMAND.NEW, text: "New optimization", enabled: false }, { id: COMMAND.OPTIMIZE, text: "Optimize route", enabled: false }], onCommand); viewer.addControlPanel({ title: "Service vehicle routes", area: "right", width: 320, controls: [{ id: CONTROL.NEW, type: "button", text: "New optimization" }, { id: CONTROL.OPTIMIZE, type: "button", text: "Optimize route" }, { id: CONTROL.SUMMARY, type: "text", label: "Summary", value: summaryText(), readOnly: true }, { id: CONTROL.COUNT, type: "number", label: "Service vehicles", value: 1, minimum: 1, maximum: 100, step: 1, decimals: 0 }, { id: CONTROL.VEHICLE, type: "combo", label: "Service vehicles", options: [], enabled: false }, { id: CONTROL.ROAD, type: "combo", label: "Road directions", options: [], enabled: false }] }, onControl); viewer.setControlEnabled(CONTROL.NEW, false); viewer.setControlEnabled(CONTROL.OPTIMIZE, false); viewer.addLogPanel("Road directions"); viewer.setEventCallback(e => { if (e.eventType === ViewerEventType.MAP_MOUSE_UP) setImmediate(() => requestSelection(e)); }); viewer.setTool(ViewerTool.PAN); viewer.setStatusText("Preparing Stockholm sample data..."); viewer.show(); viewer.processEvents(); startEventPump(); const shapefile = await ensureSampleFile(SAMPLE_URL, "stockholm.zip", "stockholm", "stockholm.shp"); if (!viewer) return; viewer.addLayer(shapefile); viewer.setLayerCoordinateSystemPreset(0, "EPSG:4326"); viewer.setCoordinateSystemPreset("EPSG:3857"); viewer.setLayerStyle(0, { lineColor: "#718684", lineWidth: 1 }); const extent = viewer.layerProjectedExtent(0); if (extent) viewer.setViewExtent(extent); viewer.setStatusText("Preparing routing graph..."); worker = fork(path.join(__dirname, "routing-worker.js"), [], { env: { ...process.env, ELECTRON_RUN_AS_NODE: "1", LOCALAPPDATA: path.join(app.getPath("temp"), "GeoKernelRouteOptimizationWorker") }, stdio: ["ignore", "pipe", "pipe", "ipc"] }); worker.stdout.on("data", d => process.stdout.write(d)); worker.stderr.on("data", d => process.stderr.write(d)); worker.on("message", handleWorker); worker.on("error", e => { viewer?.setStatusText(e.message); console.error(e.stack || e); }); worker.send({ type: "initialize", shapefile }); }
function stop() { closing = true; if (eventPump) clearInterval(eventPump); eventPump = null; worker?.kill(); worker = null; if (viewer) try { viewer.close(); } catch {} viewer = null; keeperWindow?.destroy(); keeperWindow = null; }
module.exports = { start, stop };
