"use strict";

const { ViewerWindow } = require("geokernel-electron");
const EARTH_RADIUS = 6371008.8; const MERCATOR_LIMIT = 20037508.342789244;
function mercator(p) { const lat = Math.max(-85.05112878, Math.min(85.05112878, p.y)); return { x: p.x * MERCATOR_LIMIT / 180, y: Math.log(Math.tan((90 + lat) * Math.PI / 360)) * MERCATOR_LIMIT / Math.PI }; }
function distance(a, b) { const a1 = a.y * Math.PI / 180; const a2 = b.y * Math.PI / 180; const dy = a2 - a1; const dx = (b.x - a.x) * Math.PI / 180; const v = Math.sin(dy / 2) ** 2 + Math.cos(a1) * Math.cos(a2) * Math.sin(dx / 2) ** 2; return EARTH_RADIUS * 2 * Math.atan2(Math.sqrt(v), Math.sqrt(1 - v)); }
class Heap { constructor() { this.a = []; } get size() { return this.a.length; } push(v) { this.a.push(v); let i = this.a.length - 1; while (i) { const p = Math.floor((i - 1) / 2); if (this.a[p][0] <= v[0]) break; this.a[i] = this.a[p]; i = p; } this.a[i] = v; } pop() { const r = this.a[0]; const v = this.a.pop(); if (this.a.length) { let i = 0; while (i * 2 + 1 < this.a.length) { let c = i * 2 + 1; if (c + 1 < this.a.length && this.a[c + 1][0] < this.a[c][0]) c++; if (this.a[c][0] >= v[0]) break; this.a[i] = this.a[c]; i = c; } this.a[i] = v; } return r; } }
class Engine {
  constructor(json) { const g = JSON.parse(json); this.nodes = new Map(g.nodes.map(n => [n.id, n])); this.edges = new Map(g.edges.map(e => [e.id, e])); this.out = new Map(); for (const e of g.edges) { if (!this.out.has(e.from)) this.out.set(e.from, []); this.out.get(e.from).push(e); } this.component = this.largestComponent(); }
  largestComponent() { const seen = new Set(); let best = new Set(); for (const seed of this.nodes.keys()) { if (seen.has(seed)) continue; const set = new Set([seed]); const q = [seed]; seen.add(seed); for (let i = 0; i < q.length; i++) for (const e of this.out.get(q[i]) ?? []) if (!seen.has(e.to)) { seen.add(e.to); set.add(e.to); q.push(e.to); } if (set.size > best.size) best = set; } return best; }
  reachable(start) { const set = new Set([start]); const q = [start]; for (let i = 0; i < q.length; i++) for (const e of this.out.get(q[i]) ?? []) if (!set.has(e.to)) { set.add(e.to); q.push(e.to); } return set; }
  nearest(candidates, p) { let best = null; let d = 2000; for (const id of candidates) { const n = this.nodes.get(id); const x = n ? distance(p, n) : Infinity; if (x < d) { best = n; d = x; } } return best ? { node: best, distance: d } : null; }
  distancesFrom(start, targets) { const wanted = new Set(targets); const result = new Map(); const costs = new Map([[start, 0]]); const q = new Heap(); q.push([0, start]); while (q.size && result.size < wanted.size) { const [cost, node] = q.pop(); if (cost > (costs.get(node) ?? Infinity)) continue; if (wanted.has(node)) result.set(node, cost); for (const e of this.out.get(node) ?? []) { const next = cost + e.distance; if (next >= (costs.get(e.to) ?? Infinity)) continue; costs.set(e.to, next); q.push([next, e.to]); } } return result; }
  leg(start, finish) { const costs = new Map([[start, 0]]); const previous = new Map(); const q = new Heap(); q.push([0, start]); while (q.size) { const [cost, node] = q.pop(); if (cost > (costs.get(node) ?? Infinity)) continue; if (node === finish) break; for (const e of this.out.get(node) ?? []) { const next = cost + e.distance; if (next >= (costs.get(e.to) ?? Infinity)) continue; costs.set(e.to, next); previous.set(e.to, e); q.push([next, e.to]); } } if (!costs.has(finish)) return null; const ids = []; let node = finish; while (node !== start) { const e = previous.get(node); if (!e) return null; ids.unshift(e.id); node = e.from; } const geometry = []; let total = 0; let time = 0; for (const id of ids) { const e = this.edges.get(id); total += e.distance; if (e.speedKmh > 0) time += e.distance / (e.speedKmh * 1000 / 3600); this.append(geometry, (e.geometry ?? []).map(([x, y]) => mercator({ x, y }))); } return { edgeIds: ids, geometry, distance: total, time }; }
  optimize(stops, requestedVehicles) { const targets = stops.slice(); const matrix = targets.map(id => this.distancesFrom(id, targets)); if (matrix.some((row, i) => targets.some((id, j) => i !== j && !row.has(id)))) return { error: "No connected route was found between the selected points." }; const remaining = new Set(stops.slice(1)); const order = []; let current = stops[0]; while (remaining.size) { let best = null; let value = Infinity; const row = matrix[stops.indexOf(current)]; for (const id of remaining) { const d = row.get(id) ?? Infinity; if (d < value) { value = d; best = id; } } order.push(best); remaining.delete(best); current = best; } const routeCost = values => { let sum = 0; let prev = stops[0]; for (const id of values) { sum += matrix[stops.indexOf(prev)].get(id); prev = id; } return sum + matrix[stops.indexOf(prev)].get(stops[0]); }; let improved = true; while (improved) { improved = false; const base = routeCost(order); for (let i = 0; i < order.length - 1 && !improved; i++) for (let j = i + 1; j < order.length; j++) { const candidate = order.slice(); [candidate[i], candidate[j]] = [candidate[j], candidate[i]]; if (routeCost(candidate) + 0.001 < base) { order.splice(0, order.length, ...candidate); improved = true; break; } } }
    const count = Math.max(1, Math.min(Math.floor(requestedVehicles || 1), order.length)); const buckets = Array.from({ length: count }, () => []); order.forEach((id, i) => buckets[Math.min(count - 1, Math.floor(i * count / order.length))].push(id)); const vehicles = [];
    for (let index = 0; index < buckets.length; index++) { const nodes = [stops[0], ...buckets[index], stops[0]]; const legs = []; for (let i = 1; i < nodes.length; i++) { const leg = this.leg(nodes[i - 1], nodes[i]); if (!leg) return { error: `No route was found for vehicle ${index + 1}.` }; legs.push(leg); } const geometry = []; legs.forEach(l => this.append(geometry, l.geometry)); const edgeIds = legs.flatMap(l => l.edgeIds); vehicles.push({ index, visitLabels: buckets[index].map(id => stops.indexOf(id)), legs, geometry, steps: this.steps(edgeIds), distance: legs.reduce((s, l) => s + l.distance, 0), time: legs.reduce((s, l) => s + l.time, 0) }); }
    return { vehicles, visitCount: stops.length - 1, totalDistance: vehicles.reduce((s, v) => s + v.distance, 0), totalTime: vehicles.reduce((s, v) => s + v.time, 0), longestDistance: Math.max(...vehicles.map(v => v.distance)) };
  }
  steps(ids) { const result = []; for (const id of ids) { const e = this.edges.get(id); const name = String(e.attributes?.name ?? "").trim() || "Unnamed road"; const geometry = (e.geometry ?? []).map(([x, y]) => mercator({ x, y })); const last = result.at(-1); if (last && last.name.toLowerCase() === name.toLowerCase()) { last.distance += e.distance; this.append(last.geometry, geometry); } else result.push({ name, distance: e.distance, geometry }); } return result; }
  append(target, points) { for (const p of points) { const last = target.at(-1); if (!last || last.x !== p.x || last.y !== p.y) target.push(p); } }
  select(point, lastNode) { const found = this.nearest(lastNode == null ? this.component : this.reachable(lastNode), point); return found ? { id: found.node.id, world: mercator(found.node), distance: found.distance } : null; }
}
let engine = null; function send(v) { if (process.connected) process.send(v); }
function initialize(shapefile) { let v = null; try { v = new ViewerWindow({ title: "RouteOptimization graph builder", width: 320, height: 240, navigationToolbar: false }); v.addLayer(shapefile); v.setLayerCoordinateSystemPreset(0, "EPSG:4326"); if (!v.buildRoutingGraphForLayer(0, { snapTolerance: 1e-6, undirected: true, speedFieldName: "maxspeed", nameFieldName: "name", oneWayFieldName: "oneway", defaultSpeedKmh: 50 })) throw new Error("Routing graph could not be built."); const json = v.getRoutingGraphJson(); if (!json) throw new Error("Routing graph is unavailable."); v.close(); v = null; engine = new Engine(json); send({ type: "ready", nodes: engine.nodes.size, edges: engine.edges.size }); } catch (e) { try { v?.close(); } catch {} send({ type: "error", message: e.message }); } }
process.on("message", m => { try { if (m.type === "initialize") initialize(m.shapefile); else if (m.type === "select" && engine) send({ type: "selection", id: m.id, snapped: engine.select(m.point, m.lastNode) }); else if (m.type === "optimize" && engine) send({ type: "optimization", id: m.id, result: engine.optimize(m.stops, m.vehicleCount) }); } catch (e) { send({ type: "error", id: m.id, message: e.message }); } });
process.on("disconnect", () => process.exit(0));
