"use strict";
const fs=require("fs"),path=require("path");
const LOCAL_ANALYSIS_RUNTIME=path.resolve(__dirname,"..","..","..","GeoKernel","outputs","build","Release");
const {app,BrowserWindow,dialog}=require("electron");const {AnalysisExecutor,ViewerTool,ViewerWindow}=require("geokernel-electron");const {ensureSampleFile}=require("../common/sample-data");
const IMAGES_URL="https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/object_detection_images.zip",MODEL_URL="https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/object_detection_model.zip";
const C={MODEL:1,MODEL_BROWSE:2,IMAGE:3,IMAGE_BROWSE:4,PROVIDER:5,PREVIOUS:6,POSITION:7,NEXT:8,RUN:9,PROGRESS:10,STAGE:11};
const CLASSES=[[1,"airplane","#E53935"],[2,"ship","#1E88E5"],[3,"storage_tank","#FB8C00"],[4,"baseball_diamond","#43A047"],[5,"tennis_court","#8E24AA"],[6,"basketball_court","#D81B60"],[7,"ground_track_field","#00ACC1"],[8,"harbor","#FDD835"],[9,"bridge","#3949AB"],[10,"vehicle","#6D4C41"]];
let viewer,keeper,pump,analysis,layer,images=[],index=-1,modelPath="",rasterPath="",provider="Auto",busy=false;
const style=color=>({fillColor:color,fillOpacity:90,lineColor:color,lineWidth:1.5,showLabels:true,labelField:"label",labelFontSize:11,labelColor:"#FFFFFF",labelHaloEnabled:true,labelHaloColor:"#202020",labelHaloWidth:2,labelAllowOverlap:true});
function progress(value,text){value=Math.max(0,Math.min(100,Math.round(value||0)));viewer.setControlValue(C.PROGRESS,value);viewer.setControlValue(C.STAGE,text);viewer.setStatusText(`${value}% — ${text}`);}function running(value){busy=value;[C.RUN,C.PREVIOUS,C.NEXT,C.MODEL_BROWSE,C.IMAGE_BROWSE,C.PROVIDER].forEach(id=>viewer.setControlEnabled(id,!value));}
function openSource(){layer?.close();layer=null;viewer.clearLayers();viewer.addLayerFile(rasterPath);viewer.setLayerName(0,"NWPU-VHR-10 source image");viewer.refreshLayers();viewer.fullExtent();}
function selectImage(value){if(value<0||value>=images.length)return;index=value;rasterPath=images[index];viewer.setControlValue(C.IMAGE,rasterPath);viewer.setControlValue(C.POSITION,`${index+1} / ${images.length} — ${path.basename(rasterPath)}`);openSource();}
async function run(){if(busy||!fs.existsSync(modelPath)||!fs.existsSync(rasterPath))return;running(true);progress(0,"Running tiled object detection...");try{const resultLayer=await analysis.runAiObjectDetectionToMemoryAsync({modelPackagePath:modelPath,rasterPath,provider,layerName:"object_detections",buildSpatialIndex:true,windowSize:512,overlap:256,nmsThreshold:0.3},(p,m)=>progress(p,m));const d=resultLayer.diagnostics,count=Number(d.materializedCount||0);layer?.close();layer=null;viewer.clearLayers();viewer.addLayerFile(rasterPath);if(count>0){layer=resultLayer;layer.addTo(viewer);const base=style("#FF4020");viewer.setLayerStyle(0,base);viewer.setLayerSymbolRenderer(0,{type:"categorized",field:"class_id",defaultStyle:base,categories:CLASSES.map(([value,label,color])=>({value,label,enabled:true,style:style(color)}))});}else resultLayer.close();viewer.refreshLayers();viewer.fullExtent();viewer.clearLog();viewer.appendLog(["GeoKernel AI tiled object detection","",`Provider: ${provider}`,"Window: 512, overlap: 256, NMS: 0.3",`Tiles processed: ${Number(d.tilesProcessed||0)} (${Number(d.tilesX||0)} x ${Number(d.tilesY||0)})`,`Detections: ${count}`,`Vector output: ${count>0?"in-memory layer":"no detections"}`].join("\n"));progress(100,count>0?"Inference complete":"Inference complete — no detections");}catch(error){progress(0,"Inference failed");viewer.clearLog();viewer.appendLog(`Inference failed:\n${error.message}`);dialog.showMessageBox({type:"error",title:"ObjectDetectionInference",message:error.message});}finally{running(false);}}
async function prepare(){try{running(true);const first=await ensureSampleFile(IMAGES_URL,"object_detection_images.zip","object-detection-images","1.jpg",{onDownloadProgress:value=>progress(value??0,"Downloading images..."),onExtracting:()=>progress(100,"Extracting images...")});const manifest=await ensureSampleFile(MODEL_URL,"object_detection_model.zip","object-detection-model","geokernel-model.json",{onDownloadProgress:value=>progress(value??0,"Downloading model..."),onExtracting:()=>progress(100,"Extracting model...")});modelPath=path.dirname(manifest);images=fs.readdirSync(path.dirname(first)).filter(x=>/\.jpe?g$/i.test(x)).sort((a,b)=>parseInt(a)-parseInt(b)).map(x=>path.join(path.dirname(first),x));for(const image of images){const sidecar=image.replace(/\.[^.]+$/,".jgw");if(!fs.existsSync(sidecar))fs.writeFileSync(sidecar,"1\n0\n0\n-1\n0.5\n-0.5\n","ascii");}viewer.setControlValue(C.MODEL,modelPath);selectImage(0);viewer.clearLog();viewer.appendLog(`${images.length} images and the ONNX model are ready.`);progress(0,"Ready");}catch(error){viewer.appendLog(`Sample preparation failed:\n${error.message}`);}finally{running(false);}}
async function control(id,_n,text){if(id===C.MODEL)modelPath=text||"";else if(id===C.IMAGE)rasterPath=text||"";else if(id===C.PROVIDER)provider=text||"Auto";else if(id===C.PREVIOUS)selectImage(index-1);else if(id===C.NEXT)selectImage(index+1);else if(id===C.RUN)setImmediate(run);else if(id===C.MODEL_BROWSE){const d=await dialog.showOpenDialog({properties:["openDirectory"]});if(!d.canceled){modelPath=d.filePaths[0];viewer.setControlValue(C.MODEL,modelPath);}}else if(id===C.IMAGE_BROWSE){const d=await dialog.showOpenDialog({properties:["openFile"],filters:[{name:"Raster images",extensions:["jpg","jpeg","png","tif","tiff"]}]});if(!d.canceled){rasterPath=d.filePaths[0];viewer.setControlValue(C.IMAGE,rasterPath);openSource();}}}
async function start(){keeper=new BrowserWindow({width:1,height:1,show:false});viewer=new ViewerWindow({title:"ObjectDetectionInference",width:1280,height:850,navigationToolbar:true});analysis=new AnalysisExecutor({binDir:LOCAL_ANALYSIS_RUNTIME});viewer.addControlPanel({title:"NWPU-VHR-10 object detection",area:"right",width:430,controls:[{id:C.MODEL,type:"text",label:"Model package"},{id:C.MODEL_BROWSE,type:"button",text:"Browse model..."},{id:C.IMAGE,type:"text",label:"Input image"},{id:C.IMAGE_BROWSE,type:"button",text:"Browse image..."},{id:C.PROVIDER,type:"combo",label:"Execution provider",options:["Auto","CPU","CUDA","DirectML"],value:"Auto"},{id:C.PREVIOUS,type:"button",text:"Previous image"},{id:C.POSITION,type:"text",label:"Image",readOnly:true},{id:C.NEXT,type:"button",text:"Next image"},{id:C.RUN,type:"button",text:"Run object detection inference"},{id:C.PROGRESS,type:"progress",label:"Progress",value:0},{id:C.STAGE,type:"text",label:"Stage",readOnly:true}]},control);viewer.addLogPanel("Inference diagnostics");viewer.addLegendPanel("NWPU-VHR-10 classes");viewer.setLegendItems(CLASSES.map(([value,label,color])=>({value,label,enabled:true,style:style(color)})));viewer.setTool(ViewerTool.PAN);viewer.show();pump=setInterval(()=>{viewer?.processEvents();if(viewer&&!viewer.isVisible())app.quit();},16);setImmediate(prepare);}
function stop(){if(pump)clearInterval(pump);layer?.close();viewer?.close();keeper?.destroy();viewer=keeper=analysis=layer=null;}
module.exports={start,stop};
